### ISSUE TITLE
Missing Plugin DSL example

### ISSUE THREAD

**Issue by Mazorius** [klaxit/hidden-secrets-gradle-plugin#10]
Currently Gradle prefers the plugin DSL. Therefore I would recommend to add the buildscript mechanic as optional deprecated application and tell inside the readme to use the [plugin DSL](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block).

**Comment by ben-j69** [comment]
Included in the new PR https://github.com/klaxit/hidden-secrets-gradle-plugin/pull/15

**Comment by ben-j69** [comment]
Done in https://github.com/klaxit/hidden-secrets-gradle-plugin/pull/15
