### ISSUE TITLE
Instead of writing tasks inside the apply block create extra classes for tasks

### ISSUE THREAD

**Issue by Mazorius** [klaxit/hidden-secrets-gradle-plugin#12]
You currently define all tasks specifics inside the plugin class.
It would be better to extract the task as classes and extends the DefaultTask. Something like [this](https://docs.gradle.org/current/userguide/custom_tasks.html#example_declaring_a_command_line_option)

Inside this you can use a temporary folder generated with Gradle internal mechanic `temporaryDir` which is given by task mechanics: https://docs.gradle.org/current/dsl/org.gradle.api.Task.html#org.gradle.api.Task:temporaryDir

**Comment by ben-j69** [comment]
@Mazorius what you are proposing looks better, but I did not succeed to register a task in an external file. I tried many things but I can not register un build.gradle a task from another file and I did not succeed to run it. Do you have any working example on how to register a Task extending DefaultTask ?

**Comment by Mazorius** [comment]
Will have a look and create a PR at the weekend.

**Comment by ben-j69** [comment]
@Mazorius I finally found the way to make it :
`        project.tasks.register(TASK_HIDE_SECRET, HideSecretTask::class.java)
`
I might do it later in a PR.
