### ISSUE TITLE
Utils.kt does not need any class or object definition

### ISSUE THREAD

**Issue by Mazorius** [klaxit/hidden-secrets-gradle-plugin#13]
You defined a [Utils.kt](https://github.com/klaxit/hidden-secrets-gradle-plugin/blob/99d4f61511ad4626f2e053bae9c0c55dcb164b89/src/main/kotlin/com/klaxit/hiddensecrets/Utils.kt#L8) `class` which contains a `companion object`.

I think there a 2 better solutions:

1. change it to object:

``` diff
- class Utils {
-   companion object {
+ object Utils {
...
-     }
```

2. Fully remove the block and us functions declared in a file:

``` diff
- class Utils {
-     companion object {
...
-     }
- }
```

**Comment by ben-j69** [comment]
Hello, thanks for the proposition 👍 
This change is already done in this PR : https://github.com/klaxit/hidden-secrets-gradle-plugin/pull/8 and done for CodeGenerator too.

I did not know the second solution 🥇
