### ISSUE TITLE
Gradle Plugin definitions

### ISSUE THREAD

**Issue by Mazorius** [klaxit/hidden-secrets-gradle-plugin#14]
You missed the name and description for this Gradle plugin. This will improve the informations on the plugins.gradle.com repository?

**Comment by ben-j69** [comment]
@Mazorius thanks, the project is not yet available on gradle.org.

I have created the PR, can you check it please ?

**Comment by Mazorius** [comment]
looks almost good

**Comment by ben-j69** [comment]
Done in https://github.com/klaxit/hidden-secrets-gradle-plugin/pull/15
