### ISSUE TITLE
Option to hide details from logs 

### ISSUE THREAD

**Issue by m-nogas** [klaxit/hidden-secrets-gradle-plugin#22]
Could a flag be added to prevent the logging of the secret, package name and obfuscated secret? It would be useful to hide these from our CI logs which are stored indefinitely. 
If you have a way around this in your CI process and could share some details on how you use this with your CI processes I would greatly appreciate it. 
If you are open to supporting this I could make a PR

**Comment by ben-j69** [comment]
Hello, I am interested to know why you use the plugin in your CI. Because once the files and secrets keys are added to your project you don't need to rerun commands, the C and Kotlin code should be in your repo? If it is relevant you are welcome to create a PR to add an option to hide logs.

**Comment by m-nogas** [comment]
We are trying to avoid committing the obfuscated secrets GitHub. Is that what you do?

**Comment by ben-j69** [comment]
It is not what I am doing on our private repository. The secret is in the project as an api key would be.

I understand your need, if you don't do the PR I will try to add this feature in the next version.

**Comment by ben-j69** [comment]
Hello @m-nogas , is your demand still necessary ? 

Thanks
