### ISSUE TITLE
Could not find com.android.tools.build:gradle:4.0.0

### ISSUE THREAD

**Issue by odifek** [klaxit/hidden-secrets-gradle-plugin#28]
This is what I get when trying to use the plugin in a project that uses AGP 4.1.2

Does it mean that the plugin only works for AGP 4.0.0?

**Comment by ben-j69** [comment]
Hello,

the project is using : 
`implementation("com.android.tools.build:gradle:4.0.2")
`
So where does the version 4.0.0 comes from ? How to reproduce the error ?

**Comment by inspifinity** [comment]
Same problem I just  added plugin in my gradle file (Android Studio 4.1.2 and Gradle 4.1.2):
`id "com.klaxit.hiddensecrets" version "0.1.1"`
and it throw error:
 
> Could not find com.android.tools.build:gradle:4.0.2.
> Searched in the following locations:
>   - https://plugins.gradle.org/m2/com/android/tools/build/gradle/4.0.2/gradle-4.0.2.pom
> If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { .

**Comment by ben-j69** [comment]
Hello @inspifinity thanks for the report. What are the repositories included in the gradle file of your Android project please ?

**Comment by Atr07** [comment]
@ben-j69 

i too face similar issue :

`Could not find com.android.tools.build:gradle:4.0.2.
Searched in the following locations:
  - https://plugins.gradle.org/m2/com/android/tools/build/gradle/4.0.2/gradle-4.0.2.pom
If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
Required by:
    project :app > com.klaxit.hiddensecrets:com.klaxit.hiddensecrets.gradle.plugin:0.1.1 > com.klaxit.hiddensecrets:HiddenSecretsPlugin:0.1.1
Add google Maven repository and sync project
Open File`

My gradle file :

`plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'com.klaxit.hiddensecrets' version '0.1.1'
}

android {
    compileSdkVersion 30
    buildToolsVersion "29.0.3"

    defaultConfig {
        applicationId "com.android.test"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}`

`// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = "1.4.30"
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.1.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

**Comment by ben-j69** [comment]
@Atr07 thanks for the details, could you try to add `mavenCentral()` to your repositories and tell me if it fixes your issue please ?

```
repositories {
    mavenCentral()
    google()
    jcenter()
}
```

**Comment by Atr07** [comment]
@ben-j69 tried adding mavenCentral() still the same error while syncing
```

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = "1.4.30"
    repositories {
        mavenCentral()
        google()
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.1.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by ben-j69** [comment]
@Atr07 I really think it is a repository issue, we need to reproduce it so I can fix the project. 

From what I see, jcenter is deprecated and maven should not be necessary. The link where your project is searching only contains gradle until 2.30.

I will investigate more.

**Comment by Atr07** [comment]
@ben-j69 I tried changing gradle version to 4.0.2 still same error was coming.

So I tried the legacy plugin adding method and it worked.

Gradle File :

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = "1.4.30"
    repositories {
        mavenCentral()
        google()
        jcenter()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.1.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.klaxit.hiddensecrets:HiddenSecretsPlugin:0.1.1"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

```
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'com.klaxit.hiddensecrets'
    //id "com.klaxit.hiddensecrets" version "0.1.1"
}

android {
    compileSdkVersion 30
    buildToolsVersion "29.0.3"

    defaultConfig {
        applicationId "com.android.test"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }
}

dependencies {

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}
```

**Comment by ben-j69** [comment]
Hello,

I made further tests. This issue is caused by the deprecated usage of jcenter: https://developer.android.com/studio/build/jcenter-migration

To solve this issue we will need to move to Android Gradle Plugin 4.2.0 when it will be stable.

To fix this error until the update of AGP, please you the legacy application of the plugin that do not trigger this issueas mentioned by @Atr07 .

Thanks.
