### ISSUE TITLE
Cannot Find Symbol Class Secrets

### ISSUE THREAD

**Issue by vicksWalkiria** [klaxit/hidden-secrets-gradle-plugin#30]
Hi!
I managed to install the library using the legacy instructions:

```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "com.klaxit.hiddensecrets:HiddenSecretsPlugin:0.1.1"
  }
}

apply plugin: "com.klaxit.hiddensecrets"
```

I could also generate the secrets with the ./gradlew command. Even use it in my code with no errors in the editor but when I run the app I get the following error:

error: cannot find symbol
import com.package.package.Secrets;
                                  ^
  symbol:   class Secrets
  location: package com.package.package

It's declared in the upper part of the class and it is used like this:

`params.put("client_id",new Secrets().getClientIdPre(mainActivity.getApplicationContext().getPackageName()));`

The key has already been created and the class exists. I would appreciate some help.
Thanks in advance

**Comment by ben-j69** [comment]
Hello @vicksWalkiria,

I don't know wich command you used exactly but the issue is in an import. Check if your import/package are fine in `Secrets.kt` and in the file in wich you are calling `getClientIdPre()`.

I don't think your package should be `com.package.package.Secrets`!

**Comment by vicksWalkiria** [comment]
Hello @ben-j69,

First of all, thanks for your quick answer and support. The package name was modified on purpose to protect my client's package name.

I managed to solve it. The problem was trying to use a .kt file in a java project, so I will write the solution in case some else bumps into this problem.

Project build.gradle:

```
buildscript {

    ext.kotlinVersion = '1.4.30'
```

Package build.gradle:
```

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

dependencies {
   implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
   ...
}
```

That's all folks!

**Comment by ben-j69** [comment]
@vicksWalkiria thanks for the solution, that can be helpful !
