### ISSUE TITLE
Execution failed for task ':hideSecret'

### ISSUE THREAD

**Issue by sphinx99** [klaxit/hidden-secrets-gradle-plugin#41]
Hi! I am testing this plugin. I am learning how to code in Java. I successfully imported the plugin and created some secret keys. However, when I build the app, I run into the following error:

Execution failed for task ':hideSecret'.

Extension with name 'android' does not exist. Currently registered extension names: [ext, buildScan, gradleEnterprise, _internalAndroidGradlePluginDependencyCheckerRegistered]

When calling the secret values in an activity using final String key = new Secrets()..., I get an error because Secrets() is not recognized.

Also, the copied files are save in root folder. Is there a way that those files will be saved in the default Java directory?

I am new to app development. I tried googling but I can't find a solution. I someone can help me.

Thank you in advance.

**Comment by ben-j69** [comment]
Hello @sphinx99 ,

For the android error : https://stackoverflow.com/questions/42158019/extension-with-name-android-does-not-exist-error-when-adding-kotlin-to-andro

The hidden secrets files must not be in root folder, delete cpp and kotline files first.

I think you made a mistake in the hideSecret command, params between `[]` are optional so you should try first by just using

`./gradlew hideSecret -Pkey=yourKeyToObfuscate`

Then the files should be in the correct folder of your app.
