### ISSUE TITLE
No longer installing

### ISSUE THREAD

**Issue by houmie** [klaxit/hidden-secrets-gradle-plugin#49]
Hello

This project has completely stopped working.

**build.gradle**
```
buildscript {
    ext.kotlin_version = "1.4.21"
    repositories {
        google()
        jcenter()
        maven { url  "https://adcolony.bintray.com/AdColony" }
        maven { url 'https://dl.bintray.com/ironsource-mobile/android-sdk' }
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:2.3.2"
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
        classpath "com.klaxit.hiddensecrets:HiddenSecretsPlugin:0.1.2"
    }
}
```

It gets completely messed up and throws this error.

```
Could not HEAD 'https://adcolony.bintray.com/AdColony/com/klaxit/hiddensecrets/HiddenSecretsPlugin/0.1.2/HiddenSecretsPlugin-0.1.2.pom'. Received status code 502 from server: Bad Gateway
Disable Gradle 'offline mode' and sync project
```

This happens on MacBook Pro (intel).

**Comment by ben-j69** [comment]
Hello @houmie did you find a solution ?

Your error was saying `Disable Gradle 'offline mode' and sync project`

**Comment by satyarajrapido** [comment]
Do this 

`repositories {
        google()
        maven { url "https://plugins.gradle.org/m2/" }
        jcenter()
        maven { url  "https://adcolony.bintray.com/AdColony" }
        maven { url 'https://dl.bintray.com/ironsource-mobile/android-sdk' }
    }`

Now sure what the concept is involved here, but rearranging the repositories like the above worked for me.

**Comment by ben-j69** [comment]
@houmie closing the issue since there is no news about it.
