### ISSUE TITLE
Can't build .so libraries using CMake 3.18.1

### ISSUE THREAD

**Issue by denis-bezrukov** [klaxit/hidden-secrets-gradle-plugin#51]
plugin version: 0.1.3
when running 
```
./gradlew lib.hiddensecrets:assembleRelease --rerun-tasks --no-build-cache
```

```
> Task :lib.hiddensecrets:configureCMakeRelWithDebInfo[arm64-v8a] FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib.hiddensecrets:configureCMakeRelWithDebInfo[arm64-v8a]'.
> [CXX1405] error when building with cmake using C:\Users\user\projectname\lib.hiddensecrets\src\main\cpp\CMakeLists.txt: Build command failed.
  Error while executing process C:\Users\user\AppData\Local\Android\Sdk\cmake\3.18.1\bin\cmake.exe with arguments {-HC:\Users\user\projectname\lib.hiddensecrets\src\main\cpp -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=23 -DANDROID_PLATFORM=android-23 -DANDROID_ABI=arm64-v8a -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=C:\Users\user\AppData\Local\Android\Sdk\ndk\21.4.7075529 -DCMAKE_ANDROID_NDK=C:\Users\user\AppData\Local\Android\Sdk\ndk\21.4.7075529 -DCMAKE_TOOLCHAIN_FILE=C:\Users\user\AppData\Local\Android\Sdk\ndk\21.4.7075529\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\user\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\user\projectname\lib.hiddensecrets\build\intermediates\cxx\RelWithDebInfo\166m5e59\obj\arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=C:\Users\user\projectname\lib.hiddensecrets\build\intermediates\cxx\RelWithDebInfo\166m5e59\obj\arm64-v8a -DCMAKE_BUILD_TYPE=RelWithDebInfo -BC:\Users\user\projectname\lib.hiddensecrets\.cxx\RelWithDebInfo\166m5e59\arm64-v8a -GNinja}

```

If I specify the Cmake version (a one we used before, when it worked) explicitly, it works
```
    externalNativeBuild {
        cmake {
            version "3.10.2.4988404"
        }
    }
```

Thanks in advance!

**Comment by ben-j69** [comment]
Hello @denis-bezrukov ,

I don't understand what it your goal by running this command ?

**Comment by denis-bezrukov** [comment]
@ben-j69 🤔 the goal is to build `.so` libraries. Usually it is transitively called when you try to build the app, the command I mention is a direct way to build it.

**Comment by ben-j69** [comment]
@denis-bezrukov do you succeed to use hidden secret in your app by following the readme ? I have never try this kind of build. Why would you like to build it separately like this ?

**Comment by denis-bezrukov** [comment]
@ben-j69 yes, we successfully use it. After setting it up from readme (repeated calls `./gradlew lib.hiddensecrets:hideSecret -PkeyName=name -Pkey=key` you usually call `app:build` / `app:assemble` or simply click `Run` in Android studio. All these commands internally call `assemble` on module that contain these secrets.

**Comment by ben-j69** [comment]
@denis-bezrukov indeed `./gradlew lib.hiddensecrets:assembleRelease` does not work.
If you want to look deep into it feel free to submit a PR if it is relevant. What is your use case of building `.so` like this ?
