### ISSUE TITLE
UnsatisfiedLinkError when package name has underscores

### ISSUE THREAD

**Issue by isikkema** [klaxit/hidden-secrets-gradle-plugin#52]
When the main package name includes an underscore, java looks for the incorrect function name.

Ex:
Using with `com.example.mypackage`, it looks for `Java_com_example_mypackage_Secrets_getsecretname`.
However, using with `com.example.my_package`, it looks for `Java_com_example_my_1package_Secrets_getsecretname`.

Note the `my_1package` instead of `my_package`.

This causes an UnsatisfiedLinkError when it doesn't find what it's looking for.

**Comment by ben-j69** [comment]
@isikkema thanks for the report, I will fix it in the next release ! Feel free to also create the PR for the fix ;)

**Comment by ben-j69** [comment]
@isikkema being fixed in https://github.com/klaxit/hidden-secrets-gradle-plugin/pull/53
