### ISSUE TITLE
Segmentation violation (invalid memory reference) on Android 7

### ISSUE THREAD

**Issue by jchau207** [klaxit/hidden-secrets-gradle-plugin#58]
Hello, 

In our project, `hidden-secrets` is only library that uses NDK and have any C++ code. 

A portion of our `Android 7` users are getting these errors:
```
SIGSEGV Segmentation violation (invalid memory reference) 
    /system/lib/libart.so:666192 0xa8a3fa50
```

Specially these two devices are experiencing the highest failures:
```
HOT5 (Infinix X559C)- 20.3%
TECNO K7about - 19.7%
```

Do you guys have any insight, how we may address these crashes?

**Comment by ben-j69** [comment]
Hello @jchau207 ,

what makes you think it is because of hidden secret ? libart.so is a Google library.

Thanks

**Comment by jchau207** [comment]
This error started appearing after using implementing hidden secret. Unfortunately, I can't any stack traces beyond what I posted.
