### ISSUE TITLE
Obfuscator not using full 256 bits of each byte

### ISSUE THREAD

**Issue by DawnStream** [klaxit/hidden-secrets-gradle-plugin#59]
When obfuscating the key and when decrypting it, you take the string representation of the sha256 digest. This causes the obfuscator used to be constructed from only [1-10,a-e], and not the full range of the byte values. This guarantee that some bits are never changed (e.g. the MSB, as ascii calues are always less than 127).
I suggest using the original digest value and not "format" it to string value.

**Comment by ben-j69** [comment]
Hello @DawnStream ,
thanks for the report, feel free to submit the PR to improve the lib ;)

**Comment by DawnStream** [comment]
@ben-j69 Just created a PR to fix this. Thanks for this plugin!
