### ISSUE TITLE
It is still possible to get the keys by modifying the app

### ISSUE THREAD

**Issue by Irineu333** [klaxit/hidden-secrets-gradle-plugin#61]
I did a test and managed to get the keys by modifying the app in order to make it deliver the key to me.
![image](https://user-images.githubusercontent.com/45833588/176259508-1f83bd93-b61e-455e-ab45-1e38fbeec638.png)

Also, I haven't tested it, but I wonder what would stop someone from simply taking the libsecrets.so file and running it in their application? I think a C-code level app signature check would solve both of these issues (since I lose the signature when I modify the app).

**Comment by ben-j69** [comment]
Hello @Irineu333 ,

1/ the app you are showing does not look obfuscated ? It will be much harder to do the same in a production's app.
2/ If you run a libsecrets.so in another app it won't have the correct key and package name to read the hidden keys.

**Comment by Irineu333** [comment]
1) obfuscation would make it difficult, but it would still be possible
2) what prevents someone from creating an app with the same package? in fact, it wouldn't even be necessary since the package is passed as an argument, an app with package x could hardcode a package y

a more robust way to check the package would be to pass a context and call getPackageName, but it wouldn't stop creating an app with the same package
![image](https://user-images.githubusercontent.com/45833588/176499287-31f9a2d8-cae3-45d8-8525-a6a189cf6937.png)

**Comment by Irineu333** [comment]
@ben-j69 what would this "correct key" be? did i miss something? 🤔

**Comment by Irineu333** [comment]
@ben-j69  I can't run the libsecrets.so files in an app other than the one they were compiled, but I don't know if it's my lack of knowledge or it's really not possible, but there's still the issue of tampering with the app

I'm trying to code a signature check but it's too complicated

**Comment by ben-j69** [comment]
@Irineu333 as said in Readme:

> ⚠️ Nothing on the client-side is unbreakable. So generally speaking, keeping a secret in a mobile package is not a smart idea. But when you absolutely need to, this is the best method we have found to hide it.

You should try to investigate with real obfuscated code, it is much more difficult to get what you want. It will be long and difficult to find the necessary info to reveal the hidden keys.

**Comment by kalpesh2704** [comment]
We can compare application signature at runtime inside JNI. If signature is matching then only return key else don't return key.

**Comment by Irineu333** [comment]
@kalpesh2704 It's a great solution!
