### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by mehdi-salehi** [klaxit/hidden-secrets-gradle-plugin#66]
.\gradlew build failed whit this error:

> Task :test

UtilsTest > Using encodeSecret() should > UtilsTest.encode String with special characters FAILED
    io.kotest.assertions.AssertionFailedError at UtilsTest.kt:45

"encode String with special characters" {
            val key = "@&é(§èçà)-ù,;:=#°_*%£?./+"
            Utils.encodeSecret(
                key,
                packageName
            ) shouldBe "{ 0x70, 0x45, 0xa2, 0xcc, 0x4c, 0xf5, 0x9e, 0xa5, 0x9a, 0xf0, 0xc1, 0xa6, 0x92, 0x4a, 0x4e, 0xa6, 0x8a, 0x1a, 0xc, 0x5e, 0x5, 0x14, 0xf7, 0x86, 0x6b, 0x13, 0x40, 0xf5, 0x9a, 0xc, 0x16, 0x16, 0x19 }"
        }

**Comment by ben-j69** [comment]
Hello @mehdi-salehi,

please make an effort when reporting an issue.

What version are you using ? How to reproduce ?

Thanks
