### ISSUE TITLE
how to fix this ?

### ISSUE THREAD

**Issue by sandy14362** [klaxit/hidden-secrets-gradle-plugin#71]
C:\Users\abhiv\AndroidStudioProjects\dummy\app\src\main\java\com\example\dummy\MainActivity.java:13: error: cannot find symbol
        String key = new Secrets().getTNWDPJXI(getPackageName());
                         ^
  symbol:   class Secrets
  location: class MainActivity

using in java android

**Comment by yann591** [comment]
How did you solve this problem?
