### ISSUE TITLE
Got error

### ISSUE THREAD

**Issue by Android1500** [klaxit/hidden-secrets-gradle-plugin#73]
Task '[-PkeyName=roomKey]' not found in root project 'Faker' and its subprojects.

**Comment by ben-j69** [comment]
> Task '[-PkeyName=roomKey]' not found in root project 'Faker' and its subprojects.

HELLO,

if you don't provide how you encounter this issue I can not help you.

It looks like you made a wrong command line.

**Comment by Android1500** [comment]
i use this command in android studio terminal ./gradlew hideSecret -Pkey=yourKeyToObfuscate [-PkeyName=YourSecretKeyName] and i got this above error which i mention in issue but when i not set key name it successfully create key with random string
