### ISSUE TITLE
Can't declare plugin on Android Studio Flamingo with AGP 8.0.1 and Kotlin build configuration

### ISSUE THREAD

**Issue by MaasboDev** [klaxit/hidden-secrets-gradle-plugin#75]
In this project, I'm using version catalogs as well and I tried all the options you have in the README, including the legacy plugin application, but all of them complain with an error, the legacy plugin application error is:
```
A problem occurred configuring root project 'XXXXXX'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.klaxit.hiddensecrets:HiddenSecretsPlugin:X.Y.Z.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/klaxit/hiddensecrets/HiddenSecretsPlugin/X.Y.Z/HiddenSecretsPlugin-X.Y.Z.pom
       - https://plugins.gradle.org/m2/com/klaxit/hiddensecrets/HiddenSecretsPlugin/X.Y.Z/HiddenSecretsPlugin-X.Y.Z.pom
       - https://repo.maven.apache.org/maven2/com/klaxit/hiddensecrets/HiddenSecretsPlugin/X.Y.Z/HiddenSecretsPlugin-X.Y.Z.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by ben-j69** [comment]
Hello @MaasboDev you did not replace X.Y.Z by the version of the library you want to use ?

**Comment by MaasboDev** [comment]
I did it like is explained in the README and gave me the error I posted.
```
buildscript {
    repositories {
        google()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.klaxit.hiddensecrets:HiddenSecretsPlugin:X.Y.Z"
    }
}

apply plugin: 'com.klaxit.hiddensecrets'
```

**Comment by ben-j69** [comment]
@MaasboDev you need to replace X.Y.Z by the version of the lib you want to use, like 0.2.0.

**Comment by MaasboDev** [comment]
I had no errors now adding the dependency, but when I tried to use:
```
./gradlew hideSecret -Pkey=yourKeyToObfuscate [-PkeyName=YourSecretKeyName] [-Ppackage=com.your.package]
```

Got this response:
´´´
Welcome to Gradle 8.1!

Here are the highlights of this release:
 - Stable configuration cache
 - Experimental Kotlin DSL assignment syntax
 - Building with Java 20

For more details see https://docs.gradle.org/8.1/release-notes.html

Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
Encryption of the configuration cache is enabled.
Calculating task graph as no configuration cache is available for tasks: hideSecret

0 problems were found storing the configuration cache.

See the complete report at file:///

FAILURE: Build failed with an exception.

* What went wrong:
Task 'hideSecret' not found in root project 'Marvel MD' and its subprojects.

* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s
Configuration cache entry stored.
```

I can't use Secrets().

**Comment by ben-j69** [comment]
@MaasboDev did you apply the plugin as explained in the readme ?

**Comment by MaasboDev** [comment]
In my **libs.versions.toml**:
```
[versions]
klaxit = "0.2.1"
[plugins]
klaxit = { id = "com.klaxit.hiddensecrets", version.ref = "klaxit" }
```

In my module level **build.gradle.kts** (hope is not into app):
```
alias(libs.plugins.klaxit) apply false
```

**Comment by ben-j69** [comment]
@MaasboDev please start the integration by exactly following the readme. For example le "apply false" does not looks good to me.

**Comment by MaasboDev** [comment]
I erased the "apply false" and tried again with "./gradlew hideSecret -Pkey=yourKeyToObfuscate", the result was:
```
Encryption of the configuration cache is enabled.
Calculating task graph as no configuration cache is available for tasks: hideSecret

> Configure project :
Unzip jar to /Users/XXX/XXX/XXX/build/hidden-secrets-tmp

> Task :hideSecret FAILED
secrets.cpp already exists
CMakeLists.txt already exists
sha256.hpp already exists
sha256.cpp already exists
secrets.hpp already exists
Secrets.kt not found in src/main/

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':hideSecret'.
> Extension with name 'android' does not exist. Currently registered extension names: [ext, libs, versionCatalogs]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Configuration cache problems found in this build.

10 problems were found storing the configuration cache, 1 of which seems unique.
- Task `:hideSecret` of type `org.gradle.api.DefaultTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.1/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

See the complete report at file:///Users/XXXX/XXXX/XXXX/build/reports/configuration-cache/edtw9pl0oj2k7i1dahepoif0c/ah3olnsy4axkmodwkocji2f1f/configuration-cache-report.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
2 actionable tasks: 1 executed, 1 up-to-date
Configuration cache entry discarded with 10 problems.
```

**Comment by ben-j69** [comment]
So the lib is found and now you have to fix your configuration, with something like https://stackoverflow.com/questions/42158019/extension-with-name-android-does-not-exist-error-when-adding-kotlin-to-andro

I will close this issue. Open a new one when the lib is integrated if you have issues using it.

Thanks,
