### ISSUE TITLE
How to get secret key from Groovy

### ISSUE THREAD

**Issue by auliakbarh** [klaxit/hidden-secrets-gradle-plugin#81]
to get your secret key from Java/Kotlin code by calling :

### Kotlin
```kotlin
val key = Secrets().getYourSecretKeyName(packageName)
```
### Java
```java
final String key = new Secrets().getYourSecretKeyName(getPackageName());
```

How to get secret key from Groovy (build.gradle) file?

**Comment by ben-j69** [comment]
@auliakbarh this is not the purpose of this lib, sorry !
