### ISSUE TITLE
 error: cannot find symbol

### ISSUE THREAD

**Issue by yann591** [klaxit/hidden-secrets-gradle-plugin#82]
Hi,

I have this error when I build java project

MainActivity.java:26: error: cannot find symbol
           String key = new Secrets().getMyKey(getPackageName());
                              ^
  symbol:   class Secrets
  location: class MainActivity

What is the problem ?

**Comment by ben-j69** [comment]
Hello @yann591 it looks like you did not import correctly the Secrets class in your activity.

**Comment by yann591** [comment]
Thanks for your reply @ben-j69 .

I think the problem comes from the fact that it creates a secret class in kotlin, whereas my project is in java.

Is it not possible to have this class (secret.kt) in java?

**Comment by ben-j69** [comment]
@yann591 you project should be able to run Kotlin if not outdated. In other case you can still try to convert it to java.

**Comment by yann591** [comment]
On adding kotlin support on java project, working now.

https://developer.android.com/kotlin/add-kotlin?hl=fr

Thanks for your help.
