### ISSUE TITLE
not getting the original key back

### ISSUE THREAD

**Issue by ethanonfire** [klaxit/hidden-secrets-gradle-plugin#85]
after apply ./gradlew hideSecret -Pkey=abcdefg and call val key = Secrets().getBcMuyEUv(packageName), should i get the original key: abcdefg back? 

i am not getting abcdefg back but getting some other random letters back instead.

**Comment by ben-j69** [comment]
Hello @ethanonfire are you sure you are running the prod version of your app ? You should specify package name for the different flavor of your app to be sure.

**Comment by ethanonfire** [comment]
problem solved, i entered the wrong packagename
