### ISSUE TITLE
EarlyJsError: TurboModuleRegistry.getEnforcing(...): 'PlatformConstants' could not be found. Verify that a module by this name is registered in the native binary

### ISSUE THREAD

**Issue by auliakbarh** [klaxit/hidden-secrets-gradle-plugin#90]
I'm using `"react-native": "0.76.0"`,  i follow step by step how to install hidden-secrets-gradle-plugin but I got an error:
```
EarlyJsError: TurboModuleRegistry.getEnforcing(...): 'PlatformConstants' could not be found. Verify that a module by this name is registered in the native binary
```

<img width="356" alt="image" src="https://github.com/user-attachments/assets/ed50c4df-c0b9-47d2-81c8-1e817465aa83">

can anyone help me?

**Comment by ben-j69** [comment]
Hello I don't see anything related with hidden-secrets
